version: "3.9"

services:
  ingestion:
    build: ./ingestion-service
    container_name: ingestion
    ports: ["8081:8081"]
    # environment:
    #     - FEATURE_URL=http://feature:8082/features
    # networks: [stack]

  anomaly:
    build: ./anomaly-service
    container_name: anomaly
    ports:
      - "8080:8080"


# networks:
#   stack: {}